//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppP3.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.RecurenceTypeSoap")]
    public interface RecurenceTypeSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Add", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginAdd(AppP3.ServiceReference1.RecurenceTypeModel smodel, System.AsyncCallback callback, object asyncState);
        
        bool EndAdd(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginGetDetails(System.AsyncCallback callback, object asyncState);
        
        AppP3.ServiceReference1.RecurenceTypeModel[] EndGetDetails(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetDetailsById", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginGetDetailsById(int id, System.AsyncCallback callback, object asyncState);
        
        AppP3.ServiceReference1.RecurenceTypeModel EndGetDetailsById(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/UpdateDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginUpdateDetails(AppP3.ServiceReference1.RecurenceTypeModel smodel, System.AsyncCallback callback, object asyncState);
        
        bool EndUpdateDetails(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.IAsyncResult BeginDelete(int id, System.AsyncCallback callback, object asyncState);
        
        bool EndDelete(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RecurenceTypeModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string detailField;
        
        private int daysField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
                this.RaisePropertyChanged("detail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int days {
            get {
                return this.daysField;
            }
            set {
                this.daysField = value;
                this.RaisePropertyChanged("days");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RecurenceTypeSoapChannel : AppP3.ServiceReference1.RecurenceTypeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AppP3.ServiceReference1.RecurenceTypeModel[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AppP3.ServiceReference1.RecurenceTypeModel[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetDetailsByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetDetailsByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public AppP3.ServiceReference1.RecurenceTypeModel Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((AppP3.ServiceReference1.RecurenceTypeModel)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecurenceTypeSoapClient : System.ServiceModel.ClientBase<AppP3.ServiceReference1.RecurenceTypeSoap>, AppP3.ServiceReference1.RecurenceTypeSoap {
        
        private BeginOperationDelegate onBeginAddDelegate;
        
        private EndOperationDelegate onEndAddDelegate;
        
        private System.Threading.SendOrPostCallback onAddCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDetailsDelegate;
        
        private EndOperationDelegate onEndGetDetailsDelegate;
        
        private System.Threading.SendOrPostCallback onGetDetailsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetDetailsByIdDelegate;
        
        private EndOperationDelegate onEndGetDetailsByIdDelegate;
        
        private System.Threading.SendOrPostCallback onGetDetailsByIdCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateDetailsDelegate;
        
        private EndOperationDelegate onEndUpdateDetailsDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateDetailsCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteDelegate;
        
        private EndOperationDelegate onEndDeleteDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public RecurenceTypeSoapClient() : 
                base(RecurenceTypeSoapClient.GetDefaultBinding(), RecurenceTypeSoapClient.GetDefaultEndpointAddress()) {
        }
        
        public RecurenceTypeSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(RecurenceTypeSoapClient.GetBindingForEndpoint(endpointConfiguration), RecurenceTypeSoapClient.GetEndpointAddress(endpointConfiguration)) {
        }
        
        public RecurenceTypeSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(RecurenceTypeSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
        }
        
        public RecurenceTypeSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(RecurenceTypeSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
        }
        
        public RecurenceTypeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<AddCompletedEventArgs> AddCompleted;
        
        public event System.EventHandler<GetDetailsCompletedEventArgs> GetDetailsCompleted;
        
        public event System.EventHandler<GetDetailsByIdCompletedEventArgs> GetDetailsByIdCompleted;
        
        public event System.EventHandler<UpdateDetailsCompletedEventArgs> UpdateDetailsCompleted;
        
        public event System.EventHandler<DeleteCompletedEventArgs> DeleteCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AppP3.ServiceReference1.RecurenceTypeSoap.BeginAdd(AppP3.ServiceReference1.RecurenceTypeModel smodel, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAdd(smodel, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool AppP3.ServiceReference1.RecurenceTypeSoap.EndAdd(System.IAsyncResult result) {
            return base.Channel.EndAdd(result);
        }
        
        private System.IAsyncResult OnBeginAdd(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AppP3.ServiceReference1.RecurenceTypeModel smodel = ((AppP3.ServiceReference1.RecurenceTypeModel)(inValues[0]));
            return ((AppP3.ServiceReference1.RecurenceTypeSoap)(this)).BeginAdd(smodel, callback, asyncState);
        }
        
        private object[] OnEndAdd(System.IAsyncResult result) {
            bool retVal = ((AppP3.ServiceReference1.RecurenceTypeSoap)(this)).EndAdd(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAddCompleted(object state) {
            if ((this.AddCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddCompleted(this, new AddCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddAsync(AppP3.ServiceReference1.RecurenceTypeModel smodel) {
            this.AddAsync(smodel, null);
        }
        
        public void AddAsync(AppP3.ServiceReference1.RecurenceTypeModel smodel, object userState) {
            if ((this.onBeginAddDelegate == null)) {
                this.onBeginAddDelegate = new BeginOperationDelegate(this.OnBeginAdd);
            }
            if ((this.onEndAddDelegate == null)) {
                this.onEndAddDelegate = new EndOperationDelegate(this.OnEndAdd);
            }
            if ((this.onAddCompletedDelegate == null)) {
                this.onAddCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddCompleted);
            }
            base.InvokeAsync(this.onBeginAddDelegate, new object[] {
                        smodel}, this.onEndAddDelegate, this.onAddCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AppP3.ServiceReference1.RecurenceTypeSoap.BeginGetDetails(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDetails(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppP3.ServiceReference1.RecurenceTypeModel[] AppP3.ServiceReference1.RecurenceTypeSoap.EndGetDetails(System.IAsyncResult result) {
            return base.Channel.EndGetDetails(result);
        }
        
        private System.IAsyncResult OnBeginGetDetails(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((AppP3.ServiceReference1.RecurenceTypeSoap)(this)).BeginGetDetails(callback, asyncState);
        }
        
        private object[] OnEndGetDetails(System.IAsyncResult result) {
            AppP3.ServiceReference1.RecurenceTypeModel[] retVal = ((AppP3.ServiceReference1.RecurenceTypeSoap)(this)).EndGetDetails(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDetailsCompleted(object state) {
            if ((this.GetDetailsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDetailsCompleted(this, new GetDetailsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDetailsAsync() {
            this.GetDetailsAsync(null);
        }
        
        public void GetDetailsAsync(object userState) {
            if ((this.onBeginGetDetailsDelegate == null)) {
                this.onBeginGetDetailsDelegate = new BeginOperationDelegate(this.OnBeginGetDetails);
            }
            if ((this.onEndGetDetailsDelegate == null)) {
                this.onEndGetDetailsDelegate = new EndOperationDelegate(this.OnEndGetDetails);
            }
            if ((this.onGetDetailsCompletedDelegate == null)) {
                this.onGetDetailsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDetailsCompleted);
            }
            base.InvokeAsync(this.onBeginGetDetailsDelegate, null, this.onEndGetDetailsDelegate, this.onGetDetailsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AppP3.ServiceReference1.RecurenceTypeSoap.BeginGetDetailsById(int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetDetailsById(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppP3.ServiceReference1.RecurenceTypeModel AppP3.ServiceReference1.RecurenceTypeSoap.EndGetDetailsById(System.IAsyncResult result) {
            return base.Channel.EndGetDetailsById(result);
        }
        
        private System.IAsyncResult OnBeginGetDetailsById(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return ((AppP3.ServiceReference1.RecurenceTypeSoap)(this)).BeginGetDetailsById(id, callback, asyncState);
        }
        
        private object[] OnEndGetDetailsById(System.IAsyncResult result) {
            AppP3.ServiceReference1.RecurenceTypeModel retVal = ((AppP3.ServiceReference1.RecurenceTypeSoap)(this)).EndGetDetailsById(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetDetailsByIdCompleted(object state) {
            if ((this.GetDetailsByIdCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetDetailsByIdCompleted(this, new GetDetailsByIdCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetDetailsByIdAsync(int id) {
            this.GetDetailsByIdAsync(id, null);
        }
        
        public void GetDetailsByIdAsync(int id, object userState) {
            if ((this.onBeginGetDetailsByIdDelegate == null)) {
                this.onBeginGetDetailsByIdDelegate = new BeginOperationDelegate(this.OnBeginGetDetailsById);
            }
            if ((this.onEndGetDetailsByIdDelegate == null)) {
                this.onEndGetDetailsByIdDelegate = new EndOperationDelegate(this.OnEndGetDetailsById);
            }
            if ((this.onGetDetailsByIdCompletedDelegate == null)) {
                this.onGetDetailsByIdCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetDetailsByIdCompleted);
            }
            base.InvokeAsync(this.onBeginGetDetailsByIdDelegate, new object[] {
                        id}, this.onEndGetDetailsByIdDelegate, this.onGetDetailsByIdCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AppP3.ServiceReference1.RecurenceTypeSoap.BeginUpdateDetails(AppP3.ServiceReference1.RecurenceTypeModel smodel, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateDetails(smodel, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool AppP3.ServiceReference1.RecurenceTypeSoap.EndUpdateDetails(System.IAsyncResult result) {
            return base.Channel.EndUpdateDetails(result);
        }
        
        private System.IAsyncResult OnBeginUpdateDetails(object[] inValues, System.AsyncCallback callback, object asyncState) {
            AppP3.ServiceReference1.RecurenceTypeModel smodel = ((AppP3.ServiceReference1.RecurenceTypeModel)(inValues[0]));
            return ((AppP3.ServiceReference1.RecurenceTypeSoap)(this)).BeginUpdateDetails(smodel, callback, asyncState);
        }
        
        private object[] OnEndUpdateDetails(System.IAsyncResult result) {
            bool retVal = ((AppP3.ServiceReference1.RecurenceTypeSoap)(this)).EndUpdateDetails(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateDetailsCompleted(object state) {
            if ((this.UpdateDetailsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateDetailsCompleted(this, new UpdateDetailsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateDetailsAsync(AppP3.ServiceReference1.RecurenceTypeModel smodel) {
            this.UpdateDetailsAsync(smodel, null);
        }
        
        public void UpdateDetailsAsync(AppP3.ServiceReference1.RecurenceTypeModel smodel, object userState) {
            if ((this.onBeginUpdateDetailsDelegate == null)) {
                this.onBeginUpdateDetailsDelegate = new BeginOperationDelegate(this.OnBeginUpdateDetails);
            }
            if ((this.onEndUpdateDetailsDelegate == null)) {
                this.onEndUpdateDetailsDelegate = new EndOperationDelegate(this.OnEndUpdateDetails);
            }
            if ((this.onUpdateDetailsCompletedDelegate == null)) {
                this.onUpdateDetailsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateDetailsCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateDetailsDelegate, new object[] {
                        smodel}, this.onEndUpdateDetailsDelegate, this.onUpdateDetailsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult AppP3.ServiceReference1.RecurenceTypeSoap.BeginDelete(int id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDelete(id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool AppP3.ServiceReference1.RecurenceTypeSoap.EndDelete(System.IAsyncResult result) {
            return base.Channel.EndDelete(result);
        }
        
        private System.IAsyncResult OnBeginDelete(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            return ((AppP3.ServiceReference1.RecurenceTypeSoap)(this)).BeginDelete(id, callback, asyncState);
        }
        
        private object[] OnEndDelete(System.IAsyncResult result) {
            bool retVal = ((AppP3.ServiceReference1.RecurenceTypeSoap)(this)).EndDelete(result);
            return new object[] {
                    retVal};
        }
        
        private void OnDeleteCompleted(object state) {
            if ((this.DeleteCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteAsync(int id) {
            this.DeleteAsync(id, null);
        }
        
        public void DeleteAsync(int id, object userState) {
            if ((this.onBeginDeleteDelegate == null)) {
                this.onBeginDeleteDelegate = new BeginOperationDelegate(this.OnBeginDelete);
            }
            if ((this.onEndDeleteDelegate == null)) {
                this.onEndDeleteDelegate = new EndOperationDelegate(this.OnEndDelete);
            }
            if ((this.onDeleteCompletedDelegate == null)) {
                this.onDeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteDelegate, new object[] {
                        id}, this.onEndDeleteDelegate, this.onDeleteCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override AppP3.ServiceReference1.RecurenceTypeSoap CreateChannel() {
            return new RecurenceTypeSoapClientChannel(this);
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.RecurenceTypeSoap)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.RecurenceTypeSoap)) {
                return new System.ServiceModel.EndpointAddress("http://pj1ws.azurewebsites.net/RecurenceType.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return RecurenceTypeSoapClient.GetBindingForEndpoint(EndpointConfiguration.RecurenceTypeSoap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return RecurenceTypeSoapClient.GetEndpointAddress(EndpointConfiguration.RecurenceTypeSoap);
        }
        
        private class RecurenceTypeSoapClientChannel : ChannelBase<AppP3.ServiceReference1.RecurenceTypeSoap>, AppP3.ServiceReference1.RecurenceTypeSoap {
            
            public RecurenceTypeSoapClientChannel(System.ServiceModel.ClientBase<AppP3.ServiceReference1.RecurenceTypeSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginAdd(AppP3.ServiceReference1.RecurenceTypeModel smodel, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = smodel;
                System.IAsyncResult _result = base.BeginInvoke("Add", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndAdd(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("Add", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetDetails(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetDetails", _args, callback, asyncState);
                return _result;
            }
            
            public AppP3.ServiceReference1.RecurenceTypeModel[] EndGetDetails(System.IAsyncResult result) {
                object[] _args = new object[0];
                AppP3.ServiceReference1.RecurenceTypeModel[] _result = ((AppP3.ServiceReference1.RecurenceTypeModel[])(base.EndInvoke("GetDetails", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetDetailsById(int id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("GetDetailsById", _args, callback, asyncState);
                return _result;
            }
            
            public AppP3.ServiceReference1.RecurenceTypeModel EndGetDetailsById(System.IAsyncResult result) {
                object[] _args = new object[0];
                AppP3.ServiceReference1.RecurenceTypeModel _result = ((AppP3.ServiceReference1.RecurenceTypeModel)(base.EndInvoke("GetDetailsById", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateDetails(AppP3.ServiceReference1.RecurenceTypeModel smodel, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = smodel;
                System.IAsyncResult _result = base.BeginInvoke("UpdateDetails", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndUpdateDetails(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("UpdateDetails", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDelete(int id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("Delete", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndDelete(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("Delete", _args, result)));
                return _result;
            }
        }
        
        public enum EndpointConfiguration {
            
            RecurenceTypeSoap,
        }
    }
}
